config/routes.rb
Rails.application.routes.draw do

  root to: "pets#index"

  resources :pets do
    resources :medical_records
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/medical_record.rb
class MedicalRecord < ApplicationRecord
  belongs_to :pet

  has_rich_text :symptoms
  has_rich_text :treatment

  validates :symptoms, :treatment, presence: true
end

app/models/pet.rb
class Pet < ApplicationRecord
  PET_KIND = ["Cachorro", "Gato"].freeze

  has_many :medical_records, dependent: :destroy

  validates :name, :birth_date, :breed, :pet_kind, presence: true
  validates :pet_kind, inclusion: { in: PET_KIND }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/medical_records_controller.rb
class MedicalRecordsController < ApplicationController
  before_action :find_pet
  before_action :set_medical_record, only: [:show, :edit, :update, :destroy]

  # GET /medical_records
  # GET /medical_records.json
  def index
    @medical_records = @pet.medical_records.all.page(params[:page])
  end

  # GET /medical_records/1
  # GET /medical_records/1.json
  def show
    redirect_to root_path
  end

  # GET /medical_records/new
  def new
    @medical_record = @pet.medical_records.new
  end

  # GET /medical_records/1/edit
  def edit
  end

  # POST /medical_records
  # POST /medical_records.json
  def create
    @medical_record = @pet.medical_records.new(medical_record_params)

    respond_to do |format|
      if @medical_record.save
        format.html { redirect_to pet_medical_records_path(@pet), notice: 'Medical record was successfully created.' }
        format.json { render :show, status: :created, location: pet_medical_record_path(@pet, @medical_record) }
      else
        format.html { render :new }
        format.json { render json: @medical_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medical_records/1
  # PATCH/PUT /medical_records/1.json
  def update
    respond_to do |format|
      if @medical_record.update(medical_record_params)
        format.html { redirect_to pet_medical_records_path(@pet), notice: 'Medical record was successfully updated.' }
        format.json { render :show, status: :ok, location: pet_medical_record_path(@pet, @medical_record) }
      else
        format.html { render :edit }
        format.json { render json: @medical_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medical_records/1
  # DELETE /medical_records/1.json
  def destroy
    @medical_record.destroy
    respond_to do |format|
      format.html { redirect_to pet_medical_records_path(@pet), notice: 'Medical record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.

  def find_pet
    @pet = Pet.find(params[:pet_id])
  end

  def set_medical_record
    @medical_record = @pet.medical_records.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def medical_record_params
    params.require(:medical_record).permit(:pet_id, :symptoms, :treatment)
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all.page(params[:page])
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
    redirect_to root_path
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :birth_date, :breed, :pet_kind)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetBooking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'styles', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
      <a class="navbar-brand" href="<%= root_path %>">
        <!-- img src="http://placehold.it/150x50?text=Logo" alt="" -->
        <%= image_tag("logo.png", width: 150) %>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </nav>

  <body>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/medical_records/_form.html.erb
<%= form_with(model: @medical_record, url: [@pet, @medical_record], local: true) do |form| %>
  <% if @medical_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medical_record.errors.count, "error") %> prohibited this medical_record from being saved:</h2>

      <ul>
        <% @medical_record.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset disabled>
    <div class="form-group">
      <label for="disabledTextInput">Pet</label>
      <input type="text" id="disabledTextInput" class="form-control" placeholder="<%= @pet.name %>">
    </div>
  </fieldset>

  <div class="field">
    <%= form.label :symptoms, "Sintomas" %>
    <%= form.rich_text_area :symptoms %>
  </div>

  <div class="field">
    <%= form.label :treatment, "Tratamento" %>
    <%= form.rich_text_area :treatment %>
  </div>

  <div class="actions">
    <%= form.submit "Salvar prontuário", class: "btn btn-primary float-right" %>
  </div>
<% end %>

app/views/medical_records/edit.html.erb
<h1>Editing Medical Record</h1>

<%= render 'form', medical_record: @medical_record %>
<%= link_to 'Voltar', pet_medical_records_path(@pet) %>

app/views/medical_records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prontuário de <%= @pet.name %></h1>

<div class="float-right">
  <%= link_to 'Novo Prontuário', new_pet_medical_record_path, class: "btn btn-primary active" %>
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Atendido em</th>
      <th scope="col">Sintomas</th>
      <th scope="col">Tratamento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medical_records.each do |medical_record| %>
      <tr>
        <td><%= medical_record.created_at.strftime('%d/%m/%Y %H:%M') %></td>
        <td><%= medical_record.symptoms %></td>
        <td><%= medical_record.treatment %></td>
        <td><%= link_to 'Editar', edit_pet_medical_record_path(@pet, medical_record) %></td>
        <td><%= link_to 'Remover', pet_medical_record_path(@pet, medical_record), method: :delete, data: { confirm: 'Você tem certeza?' }, class: "btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="float-right">
  <%= paginate @medical_records, window: 2 %>
</div>

app/views/medical_records/new.html.erb
<h1>Novo prontuário</h1>

<%= render 'form', pet_medical_record: @medical_record %>

<%= link_to 'Voltar', pet_medical_records_path %>

app/views/medical_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pet:</strong>
  <%= @medical_record.pet_id %>
</p>

<p>
  <strong>Symptoms:</strong>
  <%= @medical_record.symptoms %>
</p>

<p>
  <strong>Treatment:</strong>
  <%= @medical_record.treatment %>
</p>

<%= link_to 'Edit', edit_pet_medical_record_path(@medical_record) %> |
<%= link_to 'Back', pet_medical_records_path %>

app/views/pets/_form.html.erb
<%= form_with(model: pet, local: true) do |form| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
        <% pet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Nome" %>
    <%= form.text_field :name, class: "form-control", placeholder: "Nome do Pet" %>
  </div>

  <div class="field">
    <%= form.label :birth_date, "Data nascimento" %>
    <%= form.date_select :birth_date, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :breed, "Raça" %>
    <%= form.text_field :breed, class: "form-control", placeholder: "Raça do Pet" %>
  </div>

  <div class="field">
    <%= form.label :pet_kind, "Tipo" %>
    <%= form.select :pet_kind, Pet::PET_KIND, {}, { class: "custom-select" } %>
  </div>

  <div class="actions">
    <%= form.submit "Salvar Pet", class: "btn btn-primary float-right" %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editar Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Voltar', pets_path %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pets</h1>

<div class="float-right">
  <%= link_to 'Novo Pet', new_pet_path, class: "btn btn-primary active" %>
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Nome</th>
      <th scope="col">Data nascimento</th>
      <th scope="col">Raça</th>
      <th scope="col">Tipo</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td><%= pet.birth_date %></td>
        <td><%= pet.breed %></td>
        <td><%= pet.pet_kind %></td>
        <td><%= link_to 'Prontuários', pet_medical_records_path(pet) %></td>
        <td><%= link_to 'Editar', edit_pet_path(pet) %></td>
        <td><%= link_to 'Remover', pet, method: :delete, data: { confirm: 'Você tem certeza?' }, class: "btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="float-right">
  <%= paginate @pets, window: 2 %>
</div>

app/views/pets/new.html.erb
<h1>Novo Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Voltar', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @pet.birth_date %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @pet.breed %>
</p>

<p>
  <strong>Pet kind:</strong>
  <%= @pet.pet_kind %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>